/*
 * Copyright 2006 Le Duc Bao
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.castor.ddl.db2.schemaobject;

import org.castor.ddl.GeneratorException;
import org.castor.ddl.schemaobject.Field;
import org.castor.ddl.schemaobject.KeyGenerator;

/**
 * Db2 Field
 * @author <a href="mailto:leducbao@gmail.com">Le Duc Bao</a>
 */

public class Db2Field extends Field {

    /**
     * Constructor for Db2Field
     */
    public Db2Field() {
        super();
    }

    /**
     * @see org.castor.ddl.schemaobject.Field#toDDL()
     * {@inheritDoc}
     */
    public String toDDL() throws GeneratorException {
        StringBuffer buff = new StringBuffer();
        buff.append(getName()).append(" ");
        buff.append(getType().toDDL(this));
        
        if (isIdentity() || isRequired()) {
            buff.append(" NOT NULL");
        }
        
        KeyGenerator keyGen = getKeyGenerator();
        if (keyGen != null && isIdentity()) {
            
            if (KeyGenerator.IDENTITY_KEY.equalsIgnoreCase(keyGen.getName())) {
                buff.append(" GENERATED BY DEFAULT AS IDENTITY ").
                    append("START WITH 1 INCREMENT BY 1");
            }
        }

        return buff.toString();
    }

}
